kind: pipeline
type: docker
name: linux

steps:
  - name: build
    image: alptj/bdm-gcc
    commands:
      - cmake -G Ninja -B /tmp/build
      - cmake --build /tmp/build

---
kind: pipeline
type: docker
name: windows

platform:
  os: windows

steps:
  - name: build
    pull: never
    image: alptj/bdm-msvc
    environment:
      QT_DIR: C:\Qt\5.14.1\msvc2017_64
    commands:
      - c:\setup_msvc.bat amd64
      - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$env:QT_DIR" -B build .
      - cmake --build build --config Release

---
kind: pipeline
type: exec
name: mac

platform:
  os: darwin

steps:
  - name: build
    environment:
      QT_DIR: /usr/local/opt/qt
    commands:
      - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$QT_DIR -B build .
      - cmake --build build --config Release
