version: 1.0.{build}-{branch}

image:
  - Visual Studio 2017
  - Ubuntu
  - macos

platform:
  - x64

for:
-
  matrix:
    only:
      - image: Ubuntu

  install:
    - sudo apt install -y qt5-default

  build_script:
    - cmake . -B build
    - cmake --build build

-
  matrix:
    only:
      - image: Visual Studio 2017
  
  before_build:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

  build_script:
    - cmake . -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=c:\Qt\5.12.6\msvc2017_64
    - cmake --build build --config Release

  after_build:
    - cmake --build build --config Release --target package

  artifacts:
    - path: build\Kemai-*.msi

-
  matrix:
    only:
      - image: macos

  build_script:
    - cmake . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/opt/qt
    - cmake --build build --config Release

  after_build:
    - /usr/local/opt/qt/bin/macdeployqt build/src/app/Kemai.app

  artifacts:
    - path: build/src/app/Kemai.app

deploy:
  - provider: GitHub
    draft: true
    auth_token:
      secure: ZBA/qLsYwRJ9xw8sf1Q96NrJYNFdqAfDKVD7cA+okvEnjFSOt5aBk52bI+v++pIQ
    on:
      APPVEYOR_REPO_TAG: true
