version: 1.0.{build}-{branch}

image:
  - Visual Studio 2019
  - Ubuntu
  - macos

platform:
  - x64

for:
- matrix:
    only:
      - image: Ubuntu

  install:
    - sudo apt install -y qt5-default

  build_script:
    - cmake . -B build
    - cmake --build build

- matrix:
    only:
      - image: Visual Studio 2019

  before_build:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat" -arch=amd64 -vcvars_ver=14.1

  build_script:
    - cmake . -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=c:\Qt\5.12\msvc2017_64 -DOPENSSL_ROOT=C:\OpenSSL-v111-Win64
    - cmake --build build --config Release

  after_build:
    - cmake --build build --config Release --target package

  artifacts:
    - path: build\Kemai-*.msi

- matrix:
    only:
      - image: macos

  install:
    - brew install qt

  build_script:
    - cmake . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/opt/qt
    - cmake --build build --config Release

  after_build:
    - /usr/local/opt/qt/bin/macdeployqt build/src/app/Kemai.app
    - cmake --build build --config Release --target package

  artifacts:
    - path: build/Kemai-*.dmg

deploy:
  - provider: GitHub
    draft: true
    auth_token:
      secure: ZBA/qLsYwRJ9xw8sf1Q96NrJYNFdqAfDKVD7cA+okvEnjFSOt5aBk52bI+v++pIQ
    on:
      APPVEYOR_REPO_TAG: true
