version: 1.1.{build}-{branch}

image:
  - Visual Studio 2019
  - Ubuntu2004
  - macOS

platform:
  - x64

environment:
  matrix:
    - KEMAI_QT_VERSION: 6.2
    - KEMAI_QT_VERSION: 5.15

matrix:
  exclude:
    - image: Ubuntu2004
      KEMAI_QT_VERSION: 5.15
    - image: macOS
      KEMAI_QT_VERSION: 5.15

for:
  - matrix:
      only:
        - image: Ubuntu2004

    install:
      - sudo apt update
      - sudo apt install -y freeglut3-dev
      - curl -L https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -o linuxdeployqt.AppImage
      - chmod +x linuxdeployqt.AppImage

    build_script:
      - cmake --preset release -DCMAKE_PREFIX_PATH=$HOME/Qt/$KEMAI_QT_VERSION/gcc_64
      - cmake --build --preset release --target install

    after_build:
      - sudo apt install -y libxcb-shape0 libxcb-image0 libxcb-icccm4 libxcb-keysyms1 libxcb-render-util0 libgtk3.0-cil libxcb-render0
      - export LD_LIBRARY_PATH=$HOME/Qt/$KEMAI_QT_VERSION/gcc_64/lib
      - export VERSION=$(grep -oP "VERSION \K(\d+\.\d+\.\d+)" CMakeLists.txt)
      - export QT_EXTRA_PLUGINS=platforms,iconengines,wayland-decoration-client,wayland-graphics-integration-client,wayland-shell-integration,platformthemes
      - cp -r bundle/linux/* dist/
      - mv dist/bin/* dist/
      - rmdir dist/bin
      - ./linuxdeployqt.AppImage dist/Kemai -appimage -unsupported-allow-new-glibc -extra-plugins=$QT_EXTRA_PLUGINS --appimage-extract-and-run

    artifacts:
      - path: Kemai-*.AppImage

  - matrix:
      only:
        - image: Visual Studio 2019

    before_build:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat" -arch=amd64

    build_script:
      - cmake --preset release -DCMAKE_PREFIX_PATH=C:\Qt\%KEMAI_QT_VERSION%\msvc2019_64 -DOPENSSL_ROOT=C:\OpenSSL-v111-Win64
      - cmake --build --preset release --target package

    artifacts:
      - path: cmake-build-release\Kemai-*.msi

  - matrix:
      only:
        - image: macOS

    before_build:
      - brew install create-dmg ninja

    build_script:
      - cmake --preset release -DCMAKE_PREFIX_PATH=$HOME/Qt/$KEMAI_QT_VERSION/macos
      - cmake --build --preset release --target install

    after_build:
      - cd dist
      - $HOME/Qt/$KEMAI_QT_VERSION/macos/bin/macdeployqt Kemai.app -executable=Kemai.app/Contents/MacOS/Kemai -always-overwrite

    artifacts:
      - path: dist/Kemai-*.dmg

deploy:
  - provider: GitHub
    draft: true
    auth_token:
      secure: O6wonn4AR0WCMLNkDjyHEMvpb40km9Sf0vtcsHpyU8SA1tqgoJ5gQsyABRVcvRyz
    on:
      APPVEYOR_REPO_TAG: true
      KEMAI_QT_VERSION: 6.2
