version: 1.1.{build}-{branch}

image:
  - Visual Studio 2019
  - Ubuntu2004
  - macOS

platform:
  - x64

for:
  - matrix:
      only:
        - image: Ubuntu2004

    install:
      - sudo apt update
      - sudo apt install -y freeglut3-dev
      - curl -L https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -o linuxdeployqt.AppImage
      - chmod +x linuxdeployqt.AppImage

    build_script:
      - cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$HOME/Qt/6.1/gcc_64 -DCMAKE_INSTALL_PREFIX=dist
      - cmake --build build --target install

    after_build:
      - export PATH=$HOME/Qt/6.1/gcc_64/bin:$PATH
      - export LD_LIBRARY_PATH=$HOME/Qt/6.1/gcc_64/lib
      - export VERSION=$(grep -oP "VERSION \K(\d+\.\d+\.\d+)" CMakeLists.txt)
      - cp dist/bin/Kemai dist/
      - cp -r bundle/linux/* dist/
      - cp src/app/icons/kimai.png dist/kemai.png
      - ./linuxdeployqt.AppImage dist/Kemai -appimage -unsupported-allow-new-glibc --appimage-extract-and-run

    artifacts:
      - path: Kemai-*.AppImage

  - matrix:
      only:
        - image: Visual Studio 2019

    before_build:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat" -arch=amd64

    build_script:
      - cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=C:\Qt\6.2\msvc2019_64 -DOPENSSL_ROOT=C:\OpenSSL-v111-Win64 -DCMAKE_INSTALL_PREFIX=dist
      - cmake --build build --config Release --target package

    artifacts:
      - path: build\Kemai-*.msi

  - matrix:
      only:
        - image: macOS

    build_script:
      - cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$HOME/Qt/6.1/clang_64
      - cmake --build build

    after_build:
      - $HOME/Qt/6.1/clang_64/bin/macdeployqt build/src/app/Kemai.app
      - cmake --build build --target package

    artifacts:
      - path: build/Kemai-*.dmg

deploy:
  - provider: GitHub
    draft: true
    auth_token:
      secure: j3+ty+O3NBk4dHVw5CkGTtRuJRtOdgtaWTbOrCWkSnKVcevEbp6K35GcvFTik6OF
    on:
      APPVEYOR_REPO_TAG: true
