version: 1.0.{build}-{branch}

image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

for:
-
  matrix:
    only:
      - image: Ubuntu

  install:
    - apt install -y qt5-default

  build_script:
    - cmake . -B build
    - cmake --build build

-
  matrix:
    only:
      - image: Visual Studio 2017
  
  before_build:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

  build_script:
    - cmake . -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=c:\Qt\5.12.6\msvc2017_64
    - cmake --build build --config Release

  after_build:
    - cmake --build build --config Release --target package
