version: 1.0.{build}-{branch}

image:
  - Visual Studio 2019
  - Ubuntu2004
  - macos

platform:
  - x64

for:
- matrix:
    only:
      - image: Ubuntu2004

  install:
    - sudo apt update
    - sudo apt install -y qt5-default curl
    - curl -L https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -o linuxdeployqt.AppImage
    - chmod +x linuxdeployqt.AppImage

  build_script:
    - cmake . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=dist
    - cmake --build build

  after_build:
    - cmake --build build --target install
    - cp dist/bin/Kemai dist/
    - cp -r bundle/linux/* dist/
    - cp src/app/icons/kimai.png dist/kemai.png
    - ./linuxdeployqt.AppImage dist/Kemai -appimage -unsupported-allow-new-glibc --appimage-extract-and-run

  artifacts:
    - path: Kemai-*.AppImage

- matrix:
    only:
      - image: Visual Studio 2019

  before_build:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat" -arch=amd64

  build_script:
    - cmake . -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=C:\Qt\5.15\msvc2019_64 -DOPENSSL_ROOT=C:\OpenSSL-v111-Win64
    - cmake --build build --config Release

  after_build:
    - cmake --build build --config Release --target package

  artifacts:
    - path: build\Kemai-*.msi

- matrix:
    only:
      - image: macos

  install:
    - brew install qt

  build_script:
    - cmake . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/opt/qt
    - cmake --build build --config Release

  after_build:
    - /usr/local/opt/qt/bin/macdeployqt build/src/app/Kemai.app
    - cmake --build build --config Release --target package

  artifacts:
    - path: build/Kemai-*.dmg

deploy:
  - provider: GitHub
    draft: true
    auth_token:
      secure: ZBA/qLsYwRJ9xw8sf1Q96NrJYNFdqAfDKVD7cA+okvEnjFSOt5aBk52bI+v++pIQ
    on:
      APPVEYOR_REPO_TAG: true
