name: CI
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.2'

      - name: Install linux packages
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libsecret-1-dev

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release
      
      - name: Test
        run: ctest --preset release
