name: CI
on: [push, workflow_dispatch]

jobs:
  LinuxJob:
    name: Ubuntu Qt-${{ matrix.qt_version }}
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
    strategy:
      fail-fast: false
      matrix:
        qt_version: [6.5.0, 5.15.2]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Qt ${{ matrix.qt_version }}
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_version }}
          tools: 'tools_opensslv3_src'
          cache: true
          aqtversion: '==3.1.*'

      - name: Install dev dependencies
        run: sudo apt install libxss-dev libxkbcommon-x11-dev libxcb-cursor0

      - if: startsWith(matrix.qt_version, '6')
        name: Build OpenSSLv3
        run: |
          cd $IQTA_TOOLS/OpenSSLv3/src
          ./Configure && make -j3

      - name: Configure
        run: |
          cmake --preset release

      - name: Build
        run: |
          cmake --build --preset release

      - if: startsWith(matrix.qt_version, '6')
        name: Create Linux package
        run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2
          chmod +x bundle/linux/create_appimage.sh
          ./bundle/linux/create_appimage.sh -q $Qt6_DIR -b cmake-build-release -o $IQTA_TOOLS/OpenSSLv3/src

      # Create release if on built on a tag
      - if: startsWith(matrix.qt_version, '6') && startsWith(github.ref, 'refs/tags/')
        name: Create/Update release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          artifacts: 'Kemai-*.AppImage'

  WindowsJob:
    name: Windows Qt-6.5.0
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'
          tools: 'tools_opensslv3_x64'
          cache: true
          aqtversion: '==3.1.*'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: |
          cmake --preset release-win

      - name: Build
        run: |
          cmake --build --preset release-win

      - name: Create Windows package
        run: |
          cmake --build --preset release-win --target package

      # Create release if on built on a tag
      - if: startsWith(github.ref, 'refs/tags/')
        name: Create/Update release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          artifacts: 'cmake-build-release-win/Kemai-*.msi'

  MacOSJob:
    name: MacOS Qt-6.5.0
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'
          cache: true
          aqtversion: '==3.1.*'

      - name: Configure
        run: |
          cmake --preset release-macos

      - name: Build
        run: |
          cmake --build --preset release-macos

      - name: Create MacOS package
        run: |
          chmod +x bundle/macos/create_dmg.sh
          ./bundle/macos/create_dmg.sh --qt_path $Qt6_DIR --build_path cmake-build-release-macos

      # Create release if on built on a tag
      - if: startsWith(github.ref, 'refs/tags/')
        name: Create/Update release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          artifacts: 'dist/Kemai-*.dmg'
