name: CI
on: [push, workflow_dispatch]

jobs:
  job:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        qt_version: [6.2.4]
        include:
          - os: windows-latest
            qt_version: 5.15.2

    steps:
      - uses: actions@checkout@v3

      # Setup dependencies
      - uses: lukka/get-cmake@latest
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_version }}

      # Build
      - name: Configure
        run: |
          cmake --preset release

      - name: Build (Release)
        run: |
          cmake --build --preset release
