name: CI
on: [push, workflow_dispatch]

env:
  qt_version: 6.7.2

jobs:
  LinuxJob:
    name: Ubuntu
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Qt ${{ env.qt_version }}
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_version }}
          cache: true

      - name: Install dev dependencies
        run: sudo apt install libxss-dev libxkbcommon-x11-dev libxcb-cursor0

      - name: Configure
        run: |
          cmake --preset release

      - name: Build
        run: |
          cmake --build --preset release

  WindowsJob:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_version }}
          cache: true

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: |
          cmake --preset release-win

      - name: Build
        run: |
          cmake --build --preset release-win

      - name: Create Windows package
        run: |
          cmake --build --preset release-win --target package

      # Create release if on built on a tag
      - if: startsWith(github.ref, 'refs/tags/')
        name: Create/Update release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          artifacts: 'cmake-build-release-win/Kemai-*.msi'

      # Create continuous release on some branches
      - if: github.ref == 'refs/heads/develop'
        name: Create/Update prerelease
        uses: ncipollo/release-action@v1
        with:
          name: 'last develop'
          tag: 'develop'
          allowUpdates: true
          updateOnlyUnreleased: true
          prerelease: true
          artifacts: 'cmake-build-release-win/Kemai-*.msi'
      - if: github.ref == 'refs/heads/feature/98-break-ui'
        name: Create/Update prerelease
        uses: ncipollo/release-action@v1
        with:
          name: 'UI break'
          tag: '98-break-ui'
          allowUpdates: true
          updateOnlyUnreleased: true
          prerelease: true
          artifacts: 'cmake-build-release-win/Kemai-*.msi'

  MacOSJob:
    name: MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        preset: ["release-macos", "release-macos-noupdate"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_version }}
          cache: true

      - name: Configure
        run: |
          cmake --preset ${{ matrix.preset }}

      - name: Build
        run: |
          cmake --build --preset ${{ matrix.preset }}

      - name: Create MacOS package
        run: |
          cmake --build --preset ${{ matrix.preset }} --target package

      # Create release if on built on a tag
      - if: startsWith(github.ref, 'refs/tags/')
        name: Create/Update release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          artifacts: 'cmake-build-${{ matrix.preset }}/Kemai-*.dmg'

      # Create continuous release on some branches
      - if: github.ref == 'refs/heads/develop'
        name: Create/Update prerelease
        uses: ncipollo/release-action@v1
        with:
          name: 'last develop'
          tag: 'develop'
          allowUpdates: true
          updateOnlyUnreleased: true
          prerelease: true
          artifacts: 'cmake-build-${{ matrix.preset }}/Kemai-*.dmg'
      - if: github.ref == 'refs/heads/feature/98-break-ui'
        name: Create/Update prerelease
        uses: ncipollo/release-action@v1
        with:
          name: 'UI break'
          tag: '98-break-ui'
          allowUpdates: true
          updateOnlyUnreleased: true
          prerelease: true
          artifacts: 'cmake-build-${{ matrix.preset }}/Kemai-*.dmg'
