name: CI
on: [push, workflow_dispatch]

jobs:
  job:
    name: ${{ matrix.os }}_qt-${{ matrix.qt_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        qt_version: [6.2.4, 5.15.2]
        include:
          - os: windows-latest
            qt_tools: 'tools_openssl_x64'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Setup dependencies
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - if: contains(matrix.os, 'windows')
        name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt ${{ matrix.qt_version }}
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_version }}
          tools: ${{ matrix.qt_tools }}

      # Build
      - name: Configure
        run: |
          cmake --preset release

      - name: Build
        run: |
          cmake --build --preset release

      # Package Windows
      - name: Create Windows package
        if: contains(matrix.os, 'windows') && startsWith(matrix.qt_version, '6')
        run: |
          cmake --build --preset release --target package
